const AppActionsConstants = {
    LOAD_ALL_LOCATIONS: 'LOAD_ALL_LOCATIONS',
    LOAD_ALL_LOCATIONS_SUCCESS: 'LOAD_ALL_LOCATIONS_SUCCESS',
    LOAD_ALL_LOCATIONS_FAILURE: 'LOAD_ALL_LOCATIONS_FAILURE',
    GET_SUGGESTED_CITIES: 'GET_SUGGESTED_CITIES',
    GET_CURRENT_USER: 'GET_CURRENT_USER',
    GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
    GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',
};

export { AppActionsConstants };