const ProfileActionsConstants = {
    UPDATE_PROFILE_FIELD: 'UPDATE_PROFILE_FIELD',
    CHECK_PROFILE_USERNAME: 'CHECK_PROFILE_USERNAME',
    CHECK_PROFILE_USERNAME_SUCCESS: 'CHECK_PROFILE_USERNAME_SUCCESS',
    CHECK_PROFILE_USERNAME_FAILURE: 'CHECK_PROFILE_USERNAME_FAILURE',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',
    INVALID_PROFILE_INPUT: 'INVALID_PROFILE_INPUT',
};

export { ProfileActionsConstants };