const RegisterActionsConstants = {
    RESET_REGISTER_FIELDS: 'RESET_REGISTER_FIELDS',
    UPDATE_REGISTER_FIELD: 'UPDATE_REGISTER_FIELD',
    CHECK_REGISTER_USERNAME: 'CHECK_REGISTER_USERNAME',
    CHECK_REGISTER_USERNAME_SUCCESS: 'CHECK_REGISTER_USERNAME_SUCCESS',
    CHECK_REGISTER_USERNAME_FAILURE: 'CHECK_REGISTER_USERNAME_FAILURE',
    REGISTER: 'REGISTER',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    INVALID_REGISTER_INPUT: 'INVALID_REGISTER_INPUT',
};

export { RegisterActionsConstants };