const RestaurantsActionsConstants = {
    LOAD_ALL_RESTAURANTS: 'LOAD_ALL_RESTAURANTS',
    LOAD_ALL_RESTAURANTS_SUCCESS: 'LOAD_ALL_RESTAURANTS_SUCCESS',
    LOAD_ALL_RESTAURANTS_FAILURE: 'LOAD_ALL_RESTAURANTS_FAILURE',
    RESET_RESTAURANT_FIELDS: 'RESET_RESTAURANT_FIELDS',
};

export { RestaurantsActionsConstants };