const CreateModifyReviewActionsConstants = {
    CLOSE_CREATE_MODIFY_REVIEW: 'CLOSE_CREATE_MODIFY_REVIEW',
    CREATE_MODIFY_REVIEW_SCORE: 'CREATE_MODIFY_REVIEW_SCORE',
    SUBMIT_ADD_REVIEW: 'SUBMIT_ADD_REVIEW',
    SUBMIT_ADD_REVIEW_SUCCESS: 'SUBMIT_ADD_REVIEW_SUCCESS',
    SUBMIT_ADD_REVIEW_FAILURE: 'SUBMIT_ADD_REVIEW_FAILURE',
    INVALID_CREATE_MODIFY_REVIEW: 'INVALID_CREATE_MODIFY_REVIEW',
    SUBMIT_EDIT_REVIEW: 'SUBMIT_EDIT_REVIEW',
    SUBMIT_EDIT_REVIEW_SUCCESS: 'SUBMIT_EDIT_REVIEW_SUCCESS',
    SUBMIT_EDIT_REVIEW_FAILURE: 'SUBMIT_EDIT_REVIEW_FAILURE',
    CREATE_MODIFY_UPDATE_FIELD: 'CREATE_MODIFY_UPDATE_FIELD',
};

export { CreateModifyReviewActionsConstants };