const AddRestaurantActionsConstants = {
    OPEN_ADD_RESTAURANT: 'OPEN_ADD_RESTAURANT',
    CLOSE_ADD_RESTAURANT: 'CLOSE_ADD_RESTAURANT',
    SUBMIT_ADD_RESTAURANT: 'SUBMIT_ADD_RESTAURANT',
    SUBMIT_ADD_RESTAURANT_SUCCESS: 'SUBMIT_ADD_RESTAURANT_SUCCESS',
    SUBMIT_ADD_RESTAURANT_FAILURE: 'SUBMIT_ADD_RESTAURANT_FAILURE',
    UPDATE_ADD_RESTAURANT_NAME: 'UPDATE_ADD_RESTAURANT_NAME',
    UPDATE_ADD_RESTAURANT_LOCATION: 'UPDATE_ADD_RESTAURANT_LOCATION',
    UPDATE_ADD_RESTAURANT_IS_DELIVERY: 'UPDATE_ADD_RESTAURANT_IS_DELIVERY',
    UPDATE_ADD_RESTAURANT_IS_DRIVE_THRU: 'UPDATE_ADD_RESTAURANT_IS_DRIVE_THRU',
    INVALID_INPUT_ADD_RESTAURANT: 'INVALID_INPUT_ADD_RESTAURANT',
};

export { AddRestaurantActionsConstants };
