const LoginActionsConstants = {
    RESET_LOGIN_FIELDS: 'RESET_LOGIN_FIELDS',
    UPDATE_LOGIN_FIELD: 'UPDATE_LOGIN_FIELD',
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    INVALID_LOGIN_INPUT: 'INVALID_LOGIN_INPUT',
};

export { LoginActionsConstants };