const UsersActionsConstants = {
    LOAD_ALL_USERS: 'LOAD_ALL_USERS',
    LOAD_ALL_USERS_SUCCESS: 'LOAD_ALL_USERS_SUCCESS',
    LOAD_ALL_USERS_FAILURE: 'LOAD_ALL_USERS_FAILURE',
    UPDATE_SEARCH_USER_FIELD: 'UPDATE_SEARCH_USER_FIELD',
    GET_SUGGESTED_USERS_FIRST_NAME: 'GET_SUGGESTED_USERS_FIRST_NAME',
    GET_SUGGESTED_USERS_USERNAME: 'GET_SUGGESTED_USERS_USERNAME',
    SEARCH_USERS: 'SEARCH_USERS',
    SEARCH_USERS_SUCCESS: 'SEARCH_USERS_SUCCESS',
    SEARCH_USERS_FAILURE: 'SEARCH_USERS_FAILURE',
};

export { UsersActionsConstants };