const SearchRestaurantsActionsConstants = {
    SEARCH_RESTAURANT_NAME: 'SEARCH_RESTAURANT_NAME',
    SEARCH_RESTAURANT_LOCATION: 'SEARCH_RESTAURANT_LOCATION',
    SEARCH_RESTAURANT_SCORE: 'SEARCH_RESTAURANT_SCORE',
    SEARCH_RESTAURANT_CLOSER_BETTER: 'SEARCH_RESTAURANT_CLOSER_BETTER',
    SEARCH_RESTAURANTS: 'SEARCH_RESTAURANTS',
    SEARCH_RESTAURANTS_SUCCESS: 'SEARCH_RESTAURANTS_SUCCESS',
    SEARCH_RESTAURANTS_FAILURE: 'SEARCH_RESTAURANTS_FAILURE',
    GET_SUGGESTED_RESTAURANTS_NAMES: 'GET_SUGGESTED_RESTAURANTS_NAMES',
};

export { SearchRestaurantsActionsConstants };