const UserReviewsActionsConstants = {
    OPEN_MODIFY_REVIEW: 'OPEN_MODIFY_REVIEW',
    DELETE_REVIEW: 'DELETE_REVIEW',
    DELETE_REVIEW_SUCCESS: 'DELETE_REVIEW_SUCCESS',
    DELETE_REVIEW_FAILURE: 'DELETE_REVIEW_FAILURE',
    LOAD_USER_REVIEWS: 'LOAD_USER_REVIEWS',
    LOAD_USER_REVIEWS_SUCCESS: 'LOAD_USER_REVIEWS_SUCCESS',
    LOAD_USER_REVIEWS_FAILURE: 'LOAD_USER_REVIEWS_FAILURE',
};

export { UserReviewsActionsConstants };