const RestaurantActionsConstants = {
    LOAD_RESTAURANT: 'LOAD_RESTAURANT',
    LOAD_RESTAURANT_SUCCESS: 'LOAD_RESTAURANT_SUCCESS',
    LOAD_RESTAURANT_FAILURE: 'LOAD_RESTAURANT_FAILURE',
    OPEN_ADD_REVIEW: 'OPEN_ADD_REVIEW',
    UPDATE_FIELD_VALUE: 'UPDATE_FIELD_VALUE',
    SORT_REVIEWS_BY_DATE: 'SORT_REVIEWS_BY_DATE',
    SORT_REVIEWS_BY_TOPIC: 'SORT_REVIEWS_BY_TOPIC',
};

export { RestaurantActionsConstants };